version = 0.1

[dev.deploy.parameters]
stack_name = "data-processing"
resolve_s3 = true
s3_prefix = "data-processing"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
disable_rollback = true
