AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Document Processing Pipeline - Standalone Upload Lambda'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

Globals:
  Function:
    Timeout: 300
    Runtime: python3.9
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        DOCUMENT_BUCKET: !Ref DocumentBucket
        PROCESSED_DATA_BUCKET: !Ref ProcessedDataBucket
        DOCUMENT_PROCESSING_TOPIC: !Ref DocumentProcessingTopic
  Api:
    Cors:
      AllowMethods: "'POST, OPTIONS, GET'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-File-Name,X-File-Size'"
      AllowOrigin: "'*'"
    BinaryMediaTypes:
      - 'application/pdf'
      - 'application/octet-stream'
      - 'multipart/form-data'

Resources:
  # S3 Buckets
  DocumentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-documents-${Environment}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ProcessedDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-processed-${Environment}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # SNS Topic for document processing
  DocumentProcessingTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AWS::StackName}-document-processing-${Environment}'
      DisplayName: Document Processing Notifications

  # DynamoDB Table (instead of RDS for now)
  ProcessingJobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-processing-jobs-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: processing_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: processing_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: status-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  # Lambda execution role
  UploadHandlerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                Resource:
                  - !Sub 'arn:aws:s3:::${DocumentBucket}/*'
                  - !Sub 'arn:aws:s3:::${ProcessedDataBucket}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${DocumentBucket}'
                  - !Sub 'arn:aws:s3:::${ProcessedDataBucket}'
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt ProcessingJobsTable.Arn
                  - !Sub '${ProcessingJobsTable.Arn}/index/*'
        - PolicyName: SNSPublish
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref DocumentProcessingTopic

  # Upload Handler Lambda Function
  UploadHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-upload-handler-${Environment}'
      Description: Handles document upload requests
      CodeUri: ./lambda-functions/upload-handler/
      Handler: lambda_function.lambda_handler
      Role: !GetAtt UploadHandlerExecutionRole.Arn
      MemorySize: 512
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref ProcessingJobsTable
          DOCUMENT_PROCESSING_TOPIC_ARN: !Ref DocumentProcessingTopic
      Events:
        UploadApi:
          Type: Api
          Properties:
            Path: /upload
            Method: POST
        UploadApiOptions:
          Type: Api
          Properties:
            Path: /upload
            Method: OPTIONS
        StatusApi:
          Type: Api
          Properties:
            Path: /status/{processing_id}
            Method: GET

  # Test function to verify setup
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-test-${Environment}'
      Description: Test function to verify setup
      InlineCode: |
        import json
        import boto3
        import os

        def lambda_handler(event, context):
            return {
                'statusCode': 200,
                'body': json.dumps({
                    'message': 'Pipeline is working!',
                    'environment': os.environ.get('ENVIRONMENT'),
                    'bucket': os.environ.get('DOCUMENT_BUCKET'),
                    'table': os.environ.get('DYNAMODB_TABLE', 'Not configured')
                })
            }
      Handler: index.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          DOCUMENT_BUCKET: !Ref DocumentBucket
          DYNAMODB_TABLE: !Ref ProcessingJobsTable
      Events:
        TestApi:
          Type: Api
          Properties:
            Path: /test
            Method: GET

Outputs:
  ApiGatewayUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
    Export:
      Name: !Sub '${AWS::StackName}-api-url-${Environment}'

  DocumentBucketName:
    Description: Document S3 bucket name
    Value: !Ref DocumentBucket
    Export:
      Name: !Sub '${AWS::StackName}-document-bucket-${Environment}'

  ProcessedDataBucketName:
    Description: Processed data S3 bucket name  
    Value: !Ref ProcessedDataBucket
    Export:
      Name: !Sub '${AWS::StackName}-processed-data-bucket-${Environment}'

  DocumentProcessingTopicArn:
    Description: SNS Topic ARN for document processing
    Value: !Ref DocumentProcessingTopic
    Export:
      Name: !Sub '${AWS::StackName}-topic-arn-${Environment}'

  ProcessingJobsTableName:
    Description: DynamoDB table for processing jobs
    Value: !Ref ProcessingJobsTable
    Export:
      Name: !Sub '${AWS::StackName}-table-name-${Environment}'